backend:
  name: github
  repo: LykovaYuliya/lykova-site
  branch: main
  auth_type: implicit

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Блог"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Текст", name: "body", widget: "markdown" }
