backend:
  name: github
  repo: LykovaYuliya/lykova-site
  branch: main
  auth_type: oauth
  app_id: Ov23lisdzdmHbcCzxbhI
  base_url: https://lykova-site.vercel.app

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "src/content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
